/*
 * chord-demos.js: the Oh-a-Chord feature images, animated.
 *
 * Each feature figure marked data-demo="<scene>" keeps its still <img> (the
 * no-JS and reduced-motion view, and what screen readers get). When motion is
 * allowed, a <canvas> is laid over it and the matching scene from the app's
 * explainer plays there live, drawn by js/chord-reel.js (generated by
 * tools/build-chord-reel.mjs), which is only fetched once the features are
 * about to scroll into view.
 *
 * Only one scene plays at a time: whichever is most in view. The rest hold
 * their current frame and pick up from there when they take over. Nothing
 * plays while the tab is hidden, and each scene has a pause control, since it
 * loops indefinitely. Pausing the one in view pauses; it doesn't hand off.
 */
const reduced = window.matchMedia('(prefers-reduced-motion: reduce)');
const figures = [...document.querySelectorAll('figure[data-demo]')];

function loadReel() {
  if (window.OhChordReel) return window.OhChordReel.ready;
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = new URL('./chord-reel.js', import.meta.url).href;
    s.onload = () => (window.OhChordReel ? window.OhChordReel.ready.then(resolve, reject) : reject());
    s.onerror = reject;
    document.head.appendChild(s);
  });
}

function mount(reel, figure) {
  const name = figure.dataset.demo;
  const scene = reel.scenes[name];
  const frame = figure.querySelector('.frame');
  if (!scene || !frame) return null;

  const canvas = document.createElement('canvas');
  canvas.className = 'reel-canvas';
  canvas.setAttribute('aria-hidden', 'true');   // the still's alt text describes it
  const c2d = canvas.getContext('2d');

  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'media-pause';

  const demo = { name, scene, canvas, c2d, btn, figure, clock: 0.3, ratio: 0, userPaused: false, sx: 1, sy: 1 };

  const size = () => {
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const w = Math.max(1, Math.round(frame.clientWidth * dpr));
    const h = Math.max(1, Math.round(frame.clientHeight * dpr));
    if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; }
    // x and y separately, so the drawing fills the canvas to every edge
    demo.sx = w / reel.width;
    demo.sy = h / reel.height;
    draw(demo);
  };
  const label = () => {
    btn.textContent = demo.userPaused ? '▶' : '❚❚';
    btn.setAttribute('aria-label', demo.userPaused ? 'Play animation' : 'Pause animation');
  };
  btn.addEventListener('click', () => { demo.userPaused = !demo.userPaused; label(); kick(); });
  label();

  frame.append(canvas, btn);
  new ResizeObserver(size).observe(frame);
  size();
  return demo;

  function draw(d) {
    window.OhChordReel.draw(d.c2d, d.name, d.clock % d.scene.length, d.sx, d.sy);
  }
}

const demos = [];
let active = null;   // the one scene allowed to play
let last = 0, rafId = 0;

// The most visible scene wins; a near tie goes to the one nearer the middle
// of the screen, so the hand-off follows the scroll.
function choose() {
  const mid = window.innerHeight / 2;
  const centre = (d) => { const r = d.figure.getBoundingClientRect(); return Math.abs(r.top + r.height / 2 - mid); };
  let best = null;
  for (const d of demos) {
    if (d.ratio < 0.2) continue;
    if (!best || d.ratio > best.ratio + 0.05 || (Math.abs(d.ratio - best.ratio) <= 0.05 && centre(d) < centre(best))) best = d;
  }
  active = best;
}
const playing = (d) => d === active && !d.userPaused && !document.hidden;

function frame(now) {
  rafId = 0;
  const dt = last ? Math.min((now - last) / 1000, 0.1) : 0;
  last = now;
  if (active && playing(active)) {
    active.clock += dt;
    window.OhChordReel.draw(active.c2d, active.name, active.clock % active.scene.length, active.sx, active.sy);
    rafId = requestAnimationFrame(frame);
  } else last = 0;
}
function kick() {
  if (!rafId && active && playing(active)) { last = 0; rafId = requestAnimationFrame(frame); }
}

function start() {
  loadReel().then(() => {
    const reel = window.OhChordReel;
    const io = new IntersectionObserver((entries) => {
      for (const e of entries) {
        const d = demos.find((x) => x.figure === e.target);
        if (d) d.ratio = e.isIntersecting ? e.intersectionRatio : 0;
      }
      choose();
      kick();
    }, { threshold: Array.from({ length: 21 }, (_, i) => i / 20) });
    for (const figure of figures) {
      const d = mount(reel, figure);
      if (d) { demos.push(d); io.observe(figure); }
    }
    document.addEventListener('visibilitychange', kick);
  }).catch(() => { /* the stills stay: nothing to undo */ });
}

if (figures.length && !reduced.matches && 'IntersectionObserver' in window && 'ResizeObserver' in window) {
  // fetch the reel only when the features are within a screen of the viewport
  const near = new IntersectionObserver((entries) => {
    if (entries.some((e) => e.isIntersecting)) { near.disconnect(); start(); }
  }, { rootMargin: '100% 0px' });
  figures.forEach((f) => near.observe(f));
}
